sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t swagger-angular-generator .

script:
  - docker run -it swagger-angular-generator bash -c
    "npm i && npm run build &&
    npm run install:demo &&
    npm test && npm run lint"
